config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo import views
from main import views
#ex) path('main/', include('main.urls')), 메인에있는 폴더의 url을 가져오겟다

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    #path('main/', include('main.urls')),
    path('', views.main, name='main'),
    path('v1/', include('v1.urls')),
    #path('', include('main.urls')),
    path('contentform/', views.contentform, name='contentform'),
    path('price/', views.price, name='price'),
    path('pindex/', views.pindex, name='pindex'),
    #path('pybo/mypage/', views.mypage, name='mypage'),
    #path('', views.index, name='index'),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/change_password/', views.change_password, name='change_password'),
]

main/urls.py
from .views import *
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name = 'main'  #네임스페이스 추가

urlpatterns = [
    path('', views.main, name='main'),
    path('product', views.pindex, name="product"),
    path('contentform', views.contentform, name="contentform"),
    path('price', views.price, name="price"),
    #path('pindex', views.pindex, name="pindex"),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/change_password/', views.change_password, name='change_password'),
    path('product/<int:pdb_id>/', views.detail, name='pdetail'),

]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/', views.question, name='question'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', views.answer_delete, name='answer_delete'),



]

v1/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'v1'  #네임스페이스 추가

urlpatterns = [
    path('', index, name='index'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import sqlite3
# Create your models here.
# 아이디 비밀번호 이름 성별 주민 연락처 이메일 주소


 #class Usera(models.Model):
   # name = models.CharField(max_length=20)
  #  email = models.EmailField()
    #password = models.TextField()
   # Sex = models.CharField(max_length=5)
   # phone = models.TextField()
  #  address = models.TextField()











#class Board(models.Model):
 #    subject = models.CharField(max_length=200)
 #    content = models.TextField()
 #    create_date = models.DateTimeField()
   #  author = models.ForeignKey(User, on_delete=models.CASCADE)
  #   hits = models.PositiveIntegerField(default=0)
     #제목 반환
 #    def __str__(self):
  #       return self.subject
     #조회수
    # @property
   #  def update_counter(self):
    #     self.hits += 1
   #      self.save()


class King(models.Model):
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    http = models.CharField(max_length=100)

class uptest(models.Model):
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    http = models.CharField(max_length=100)

class taintain(models.Model):
    brand = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    maintain = models.IntegerField()

class lastup(models.Model):
    brand = models.CharField(max_length=100,null=True)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    http = models.CharField(max_length=100,null=True)
    eatday = models.CharField(max_length=100,null=True)
    cat = models.CharField(max_length=100)
    vo1 = models.CharField(max_length=100,null=True)
    vo2 = models.CharField(max_length=100,null=True)
    vo3 = models.CharField(max_length=100,null=True)
    vo4 = models.CharField(max_length=100,null=True)
    vo5 = models.CharField(max_length=100,null=True)
    vo6 = models.CharField(max_length=100,null=True)
    vo7 = models.CharField(max_length=100,null=True)
    vo8 = models.CharField(max_length=100,null=True)
    vo9 = models.CharField(max_length=100,null=True)
    vt1 = models.CharField(max_length=100,null=True)
    vt2 = models.CharField(max_length=100,null=True)
    vt3 = models.CharField(max_length=100,null=True)
    vt4 = models.CharField(max_length=100,null=True)
    vt5 = models.CharField(max_length=100,null=True)
    vt6 = models.CharField(max_length=100,null=True)
    vt7 = models.CharField(max_length=100,null=True)
    vt8 = models.CharField(max_length=100,null=True)
    vt9 = models.CharField(max_length=100,null=True)
    vp1 = models.CharField(max_length=100,null=True)
    vp2 = models.CharField(max_length=100,null=True)
    vp3 = models.CharField(max_length=100,null=True)
    vp4 = models.CharField(max_length=100,null=True)
    vp5 = models.CharField(max_length=100,null=True)
    vp6 = models.CharField(max_length=100,null=True)
    vp7 = models.CharField(max_length=100,null=True)
    vp8 = models.CharField(max_length=100,null=True)
    vp9 = models.CharField(max_length=100,null=True)
    vpsum = models.CharField(max_length=100,null=True)
    vpr1 = models.IntegerField(null=True)
    vpr2 = models.IntegerField(null=True)
    vpr3 = models.IntegerField(null=True)
    vpr4 = models.IntegerField(null=True)
    vpr5 = models.IntegerField(null=True)
    vpr6 = models.IntegerField(null=True)
    vpr7 = models.IntegerField(null=True)
    vpr8 = models.IntegerField(null=True)
    vpr9 = models.IntegerField(null=True)
    vprsum = models.IntegerField(null=True)
    vprsumr = models.IntegerField(null=True)
    vtr1 = models.IntegerField(null=True)
    vtr2 = models.IntegerField(null=True)
    vtr3 = models.IntegerField(null=True)
    vtr4 = models.IntegerField(null=True)
    vtr5 = models.IntegerField(null=True)
    vtr6 = models.IntegerField(null=True)
    vtr7 = models.IntegerField(null=True)
    vtr8 = models.IntegerField(null=True)
    vtr9 = models.IntegerField(null=True)
    vtrsum = models.IntegerField(null=True)
    vtrsumr = models.IntegerField(null=True)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User


#class PostSearchForm(forms.Form):
    #search_word = forms.CharField(label='Search Word')

#class UserInfoForm(forms.ModelForm):
    #class Meta:
     #   model = User
     #   fields =['name','email', 'password']
    #    widgets = {
     #       'name' : forms.TextInput(attrs={
      #          'class' : "form-control",
      #          'style' : "max-width: 300px",
      #          'placeholder' : '아이디 입력'
        #    }),
      #      'email' : forms.EmailInput(attrs={
      #          'class' : "form-control",
     #           'style' : 'max-width: 300px',
    #            'placeholder' : '이메일'
      #      }),
      #      'password' : forms.PasswordInput(attrs={
        #        'class' : "forms-control",
      #          'style' : 'max-width:200px',
           #     'placeholder' : '비밀번호 입력'
    #        }),
      #  }
    #    def __int__(self, *args, **kwargs):
     #       super(UserInfoForm,self).__init__(*args, **kwargs)
    #        self.fields['name'].widget.attrs['maxlength'] = 5
    #        self.fields['password'].widget.attrs['maxlength'] = 12

main/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import HttpResponse
from django.db.models import Q
# from .models import User
# from .models import King
# from .models import Board
from django.core.paginator import Paginator
from .models import uptest,lastup,taintain
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.csrf import csrf_exempt




import main.models
import csv
# Create your views here.
#def main2(request):
   # if request.method =="POST":
       # form = UserInfoForm(request.POST)
        #if form.is_valid():
          #  new_user = User.objects.create_user(**form.cleaned_data)
          #  login(request, new_user)
           # return render(request,'main/main_form.html', {'form' : UserInfoForm})
      #  else:
    #        return HttpResponse('사용자 명이 이미 존재합니다')
    #else:
       # form = UserInfoForm()
        #return render(request, 'main/main_form.html', {'form' : UserInfoForm})


def main(request):
    return render(request, 'main/main_form.html')

def product(request):
    return render(request, 'main/product.html')

def contentform(request):
   # path = 'C:\yi\phceeeeeee.csv'
   # file = open(path)
   # reader = csv.reader(file)
   # list = []
   # for row in reader:
   #     list.append(main.models.uptest(brand=row[0], name=row[1], price=row[2], http=row[3]))
   # main.models.uptest.objects.bulk_create(list)
   page = request.GET.get('page','1')  # GET 방식으로 정보를 받아오는 데이터
   kw=request.GET.get('kw','') #검색어 .order_by('vprsumr')
   board_list = taintain.objects.order_by('-maintain')  # models.py Board 클래스의 모든 객체를 board_list에 담음
     # Paginator(분할될 객체, 페이지 당 담길 객체수)
     # 페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
   if kw:
       board_list=board_list.filter(
           Q(name__icontains=kw) |
           Q(maintain__icontains=kw)

           #Q(price__maintain=kw)
       ).distinct()
   paginator = Paginator(board_list, 10)
   page_obj = paginator.get_page(page)
    #pdb_list = uptest15.objects.order_by('id') #하이픈(-) 붙이면 내림차순 안 붙이면 오름차순
   context = {'p_list': page_obj, 'kw':kw}
   return render(request, 'main/contentform.html', context)


#def price(request):
    #return render(request, 'main/price.html')

def pindex(request):
   # path = 'C:\yi\phceeeeeee.csv'
   # file = open(path)
   # reader = csv.reader(file)
   # list = []
   # for row in reader:
   #     list.append(main.models.uptest(brand=row[0], name=row[1], price=row[2], http=row[3]))
   # main.models.uptest.objects.bulk_create(list)
   page = request.GET.get('page','1')  # GET 방식으로 정보를 받아오는 데이터
   kw=request.GET.get('kw','') #검색어
   ckw = request.GET.get('ckw', '')  # 검색어
   board_list = lastup.objects.all()  # models.py Board 클래스의 모든 객체를 board_list에 담음
     # Paginator(분할될 객체, 페이지 당 담길 객체수)
     # 페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
   if kw:
       board_list=board_list.filter(
           Q(brand__icontains=kw)|
           Q(cat__icontains=kw) |
           Q(name__icontains=kw)
       ).distinct()
   if ckw:
       board_list = board_list.filter(

           Q(cat__icontains=ckw)

       ).distinct()
   paginator = Paginator(board_list, 10)
   page_obj = paginator.get_page(page)
    #pdb_list = uptest15.objects.order_by('id') #하이픈(-) 붙이면 내림차순 안 붙이면 오름차순
   context = {'p_list': page_obj, 'kw':kw}
   return render(request, 'main/product.html', context)


def price(request):
   # path = 'C:\yi\phceeeeeee.csv'
   # file = open(path)
   # reader = csv.reader(file)
   # list = []
   # for row in reader:
   #     list.append(main.models.uptest(brand=row[0], name=row[1], price=row[2], http=row[3]))
   # main.models.uptest.objects.bulk_create(list)
   page = request.GET.get('page','1')  # GET 방식으로 정보를 받아오는 데이터
   kw=request.GET.get('kw','') #검색어
   ckw = request.GET.get('ckw', '')  # 검색어
   board_list = lastup.objects.order_by('vprsumr')  # models.py Board 클래스의 모든 객체를 board_list에 담음
     # Paginator(분할될 객체, 페이지 당 담길 객체수)

   if kw:
       board_list=board_list.filter(
           Q(vprsumr__icontains=kw)|

           Q(price__icontains=kw)
       ).distinct()
   if ckw:
       board_list = board_list.filter(

           Q(cat__icontains=ckw)

       ).distinct()
   paginator = Paginator(board_list, 10)
   page_obj = paginator.get_page(page)  # 페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
   #pdb_list = uptest15.objects.order_by('id') #하이픈(-) 붙이면 내림차순 안 붙이면 오름차순
   context = {'p_list': page_obj, 'kw':kw}
   return render(request, 'main/price.html', context)





def mypage(request):
    return render(request, 'main/mypage.html')
@login_required(login_url='common:login')
@csrf_exempt
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, '비밀번호 변경이 완료되었습니다.')
            return redirect('pybo:mypage')
        else:
            messages.error(request, '다시 입력해주세요.')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'change_password.html', context)


def detail(request, pdb_id):
    pdetail = lastup.objects.get(id=pdb_id)
    context = {'p_list': pdetail}
    return render(request, 'main/product_detail.html', context)

    return render(request, '', context)

templates/main/main_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vita main</title>
    <!-- 반응형 적용 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script	src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script	src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

<script>
$(document).ready(function() {
    $('.slider').bxSlider({
        auto : true,
        speed : 1000,
        pause : 2000,
        mode : 'horizontal',
        pager : false,
        autoHover : true,
    });
});
</script>

</head>
<body>

  {% extends 'base.html' %} <!-- 템플릿 상속 -->
  {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">
  {% block content %}
    <div class="box-1">
        <button class="main_button">
            <a class = "aa" href="{% url 'main:product' %}">상품</a>
        </button>
        <button class="main_button">
            <a class = "aa" href="{% url 'main:price' %}">가격 랭킹</a>
        </button>
        <button class="main_button">
            <a class = "aa" href="{% url 'main:contentform' %}">함유량 랭킹</a>
        </button>
        <button class="main_button">
            <a class = "aa" href="{% url 'pybo:question' %}">게시판</a>
        </button>
    </div>>
    <div style="width:68%; margin:auto;"  >
        <div class="slider" style="width:80%; height:400px;">
        <div ><img src="/static/imgs/images01.jpg" /></div>
        <div ><img src="/static/imgs/images02.jpg" /></div>
        <div ><img src="/static/imgs/images03.jpg" /></div>
        <div><img src="/static/imgs/images05.jpg" /></div>
        <div><img src="/static/imgs/images06.jpg" /></div>
        <div><img src="/static/imgs/images04.jpg" /></div>
        </div>
    </div>

    <hr>
    <footer>
        <div class="footer-1">
            <h6 style="color:DodgerBlack">주소:서울특별시 서초구 동작대로 132 안석빌딩 9층</h6>
            <h8> 전화번호:02-599-8697</h8>
            <h8><p>Project: 3Group</p> </h8>
            <!--<a href="zz@naver.com">zz@naver.com</a>-->
        </div>
    </footer>
  {% endblock %}

</body>
</html>

templates/main/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vita Mypage</title>
</head>
<body>
  {% extends 'base.html' %} <!-- 템플릿 상속 -->
  {% block content %}
  <div id="container-5">
    <div id="left-sidebar">
      <div id="wrapper" style="width=100%;">
          <div style="width:10%; height:80%; float:left;">
              <div class="topbar" style="position: absolute; margin-left:50px; top:25%;">
              <div class="left_sub_menu">
                  <div class="sub_menu">
                  <ul class="big_menu">
                      <li><button class="btn1">
                          <a class = "aa" href="{% url 'main:product' %}">상품</a>
                      </button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'main:price' %}">가격 랭킹</a></button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'main:contentform' %}">함유량 랭킹</a></button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'pybo:question' %}">게시판</a></button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'main:mypage' %}" >마이 페이지</a></button></li>
                  </ul>
                  </div>
              </div>
          </div>

          </div>

      <br>
      <br>
      <hr>
      </div>

    </div>
    <div id="center-sidebar" style="text-align:center">
            <h1>MY PAGE</h1>
        <div>
            <li><a href="{% url 'main:change_password' %}">비밀번호 변경</a></li>
            <li><a>개인정보 수정</a></li>
            <li><a>찜목록 관리</a></li>
            <li><a>후원하기</a></li>
            <li><a>회원탈퇴</a></li>
        </div>
    </div>
    <div id="right-sidebar">
    </div>
  </div>
      <hr>
    <footer>
        <div class="footer-1">
            <h6 style="color:DodgerBlack">주소:서울특별시 서초구 동작대로 132 안석빌딩 9층</h6>
            <h8> 전화번호:02-599-8697</h8>
            <h8><p>Project: 3Group</p> </h8>
            <!--<a href="zz@naver.com">zz@naver.com</a>-->
        </div>
    </footer>
    {% endblock %}

</body>
</html>

templates/main/pdblist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
{% load humanize %}

    <div class="container my-2">
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>No</th>
                <th>브랜드명</th>
                <th>제품명</th>
                <th>가격</th>
                <th>구매링크</th>
            </tr>
            </thead>
            <tbody>
            {% if p_list %}
            {% for pdb in p_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ pdb.brand }}</td>
                <td>{{ pdb.name }}</td>
                <td>{{ pdb.price|intcomma }}</td>
                <td><a href="{{ pdb.http }}">링크</a></td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td>상품목록이 없습니다.</td>
            </tr>
            {% endif %}

            </tbody>
        </table>
    </div>

{% endblock %}
</body>

</html>

templates/main/price.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vita Price</title>
</head>
<body>
  {% extends 'base.html' %} <!-- 템플릿 상속 -->
  {% block content %}
  {% load humanize %}
  <div id="container-5">
    <div id="left-sidebar">
      <div id="wrapper" style="width=100%;">
      <div class="topbar" style="position: absolute; margin-left:50px; top:25%;">
          <div class="left_sub_menu">
              <div class="sub_menu">
                  <ul class="big_menu">
                      <li><button class="btn1">
                          <a class = "aa" href="{% url 'main:product' %}">상품</a>
                      </button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'main:price' %}">가격 랭킹</a></button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'main:contentform' %}">함유량 랭킹</a></button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'pybo:question' %}">게시판</a></button></li>
                      <li><button class="btn1"><a class = "aa" href="{% url 'main:mypage' %}" >마이 페이지</a></button></li>
                  </ul>
              </div>
          </div>


      </div>

      <br>
      <br>
      <hr>
      </div>

    </div>
    <div id="center-sidebar" style="text-align:center">
                        <button class="category-link">멀티비타민</button>
                        <button class="category-link">비타민A</button>
                        <button class="category-link">비타민B</button>
                        <button class="category-link">비타민C</button>
                        <button class="category-link">비타민D</button>
                        <button class="category-link">비타민E</button>
                        <button class="category-link">비오틴</button>
                        <button class="category-link">기타비타민</button>
        <div style="text-align:right;">
            <div class="col-4">
                <div class="input-group">
                    <input type="text" id="search_kw" placeholder="가격" class="form-control" value="{{ kw|default_if_none:''}}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                        <form id="searchForm" action="{% url 'main:price' %}" method="get" >
                            <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
                            <input type="hidden" id="ckw" name="ckw" value="{{ kw|default_if_none:'' }}">
                            <input type="hidden" id="page" name="page" value="{{ page }}">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <table class="container my-3">
            총 {{ p_list.paginator.count }} 건 출력되었습니다.
            <thead>
        <table class="table">
            <thead>
            <tr class="table-warning text-center">
                <th>가성비랭킹</th>
                <th>브랜드명</th>
                <th>제품명</th>
                <th>가격</th>

                <th>구매링크</th>
            </tr>
            </thead>
            <tbody>
            {% if p_list %}
            {% for pdb in p_list %}
            <tr>
                <td>{{ pdb.vprsumr|intcomma}}</td>
                <td>{{ pdb.brand }}</td>
                <td>{{ pdb.name }}</td>
                <td>{{ pdb.price|intcomma }}</td>

                <td><a href="{{ pdb.http }}">링크</a></td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td>상품목록이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <table>
            <!-- 페이징처리 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if p_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ p_list.previous_page_number }}" href="javascript:void(0)">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in p_list.paginator.page_range %}
                {% if page_number >= p_list.number|add:-5 and page_number <= p_list.number|add:5 %}
                {% if page_number == p_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if p_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ p_list.next_page_number }}" href="javascript:void(0)">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            </thead>
        </table>
    </div>
      <!-- 페이징처리 끝 -->
    <script type='text/javascript'>
        // 야매 카테고리 시작 --
[...document.getElementsByClassName("category-link")].forEach((element) => {
    element.addEventListener('click', (event) => {
        document.getElementById('ckw').value = event.target.innerText
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        if (document.getElementById('ckw').value) {
            document.getElementById('searchForm').submit();
        }
    });
});
// 야매 카테고리 종료 --
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
        $(document).ready(function() {
            $( "select[name=month]" ).val( "{{ month_text }}" );
            $('select[name=month]').change(function () {
            console.log($('select[name=month]').val());
            month = $('select[name=month]').val();
            $('.form').submit();
        });
    });
    </script>
      <div id="right-sidebar"></div>>
  </div>
    <footer>
        <div class="footer-1">
            <h6 style="color:DodgerBlack">주소:서울특별시 서초구 동작대로 132 안석빌딩 9층</h6>
            <h8> 전화번호:02-599-8697</h8>
            <h8><p>Project: 3Group</p> </h8>
            <!--<a href="zz@naver.com">zz@naver.com</a>-->
        </div>
    </footer>

  </div>
{% endblock %}
</body>
</html>

templates/main/searched.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}
<form method="GET" action="{% url 'search' %}">
  <!--pagenation-->
  <div class="pagination">
    {% if posts.has_previous %}
      <a href="?page=1&search={{search}}">First</a>
      <a href="?page={{posts.previous_page_number}}&search={{search}}">Previous</a>
    {% endif %}

    <span>{{posts.number}} / {{posts.paginator.num_pages}}</span>

    {% if posts.has_next %}
      <a href="?page={{posts.next_page_number}}&search={{search}}">Next</a>
      <a href="?page={{posts.paginator.num_pages}}&search={{search}}">Last</a>
    {% endif %}
  </div>

  <!--검색-->
  <div id="search">
    <input name="search" type="text">
    <button class="btn btn-primary" type="submit">검색</button>
  </div>
  </form>
{% block content %}
<h1>Blog Search</h1>
<br>


{% endblock %}

</body>
</html>