config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo import views
from main import views
#ex) path('main/', include('main.urls')), 메인에있는 폴더의 url을 가져오겟다

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    #path('main/', include('main.urls')),
    path('', views.main, name='main'),
    path('v1/', include('v1.urls')),
    #path('', include('main.urls')),
    path('contentform/', views.contentform, name='contentform'),
    path('price/', views.price, name='price'),
    path('pindex/', views.pindex, name='pindex'),
    #path('pybo/mypage/', views.mypage, name='mypage'),
    #path('', views.index, name='index'),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/change_password/', views.change_password, name='change_password'),
]

main/urls.py
from .views import *
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name = 'main'  #네임스페이스 추가

urlpatterns = [
    path('', views.main, name='main'),
    path('product', views.pindex, name="product"),
    path('contentform', views.contentform, name="contentform"),
    path('price', views.price, name="price"),
    #path('pindex', views.pindex, name="pindex"),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/change_password/', views.change_password, name='change_password'),
    path('product/<int:pdb_id>/', views.detail, name='pdetail'),

]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/', views.question, name='question'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>', views.answer_delete, name='answer_delete'),



]

v1/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'v1'  #네임스페이스 추가

urlpatterns = [
    path('', index, name='index'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, null=True, default='', on_delete=models.CASCADE) #기존모델을 속성으로 연결 포린지키
    hits = models.PositiveIntegerField(default=0)
    #제목 반환
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용'
        }

pybo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Question, Answer
from django.core.paginator import Paginator
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
#인덱스랑 앤서모디파이 퀘스천모디파이
def index(request):
    page = request.GET.get('page', '1') #페이지
    kw = request.GET.get('kw', '') #검색어
    question = Question.objects.all
    question_list=Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject_icontains=kw)|
            Q(content_icontains=kw)
        ).distinct()

    context = {'question': question, 'kw' : kw}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    #조회수카운트
    question.hits += 1
    question.save()

    return render(request, 'pybo/question_detail.html', context)

#요청게시판
def question(request):
    page = request.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10) # 한페이지당 10개씩
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)

#요청게시판-게시글등록
@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:question')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

#요청게시판 - 게시글 수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

#요청게시판 - 게시글 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:question')

#요청게시판-답글달기
@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo:question_detail.html', context)

#요청게시판 - 답글 삭제
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

templates/pybo/answer_form.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
</head>

<body>
{% extends 'base.html' %}
{% block content %}

<div class="container my-1 border">
  <h5 class="my-3 border-bottom pb-2">답변 수정</h5>

  <form method="post">
    {% csrf_token %}
      <div class="form-group">
          <textarea id="summernote" class="form-control" name="content">
              {{ form.content.value|default_if_none:'' }}
          </textarea>
          <script>
            $('#summernote').summernote({
              placeholder: '내용을 입력하세요',
              tabsize: 2,
              height: 300
            });
          </script>
      </div>
    <button type="submit" class="btn btn-warning">저장하기</button>
  </form>
</div>

{% endblock %}
</body>
</html>

templates/pybo/question_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
</head>
<body>
{% extends 'base.html' %}
{% block content %}

<!-- 게시글 상세보기 창 -->
<div class="container my-1 border">
    <!-- 오류 메세지 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <div class="row">
        <table class="table">
            <thead>
                <!-- 상단 제목 부분-->
                <div class="container">
                    <div class="row">
                        <div class="col-12" style="font-size:x-large;">
                            {{ question.subject }}
                        </div>
                        <div class="col-12">
                            {{ question.author.username }}
                        </div>
                        <div class="col-12" style="font-size:x-small;">
                            {{ question.create_date }}
                            조회 {{ question.hits }}
                        </div>
                    </div>
                </div>
            </thead>
            <!-- 게시글 내용 부분 -->
            <tbody>
                <tr style="height:300px;">
                    <td> {{ question.content|safe }} </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- 게시글 수정/삭제 버튼 -->
    <div class="my-3">
        {% if request.user == question.author %}
        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm">수정하기</a>
        <a href="javascript:void(0)" class="delete btn btn-sm" data-uri="{% url 'pybo:question_delete' question.id  %}">삭제하기</a>
        {% endif %}
    </div>
</div>

<!-- 답변 -->
<div class="container my-1 border">
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text text-dark" style="white-space: pre-line;">{{ answer.content|safe }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <!-- 답변 수정 버튼 -->
            <div class="my-3">
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm">수정하기</a>
                <a href="#" class="delete btn btn-sm" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제하기</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    </ul>
</div>
    <form action="{% url 'pybo:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <textarea id="summernote" class="form-control" name="content">
            {{ form.content.value|default_if_none:'' }}
        </textarea>
        <script>
        $('#summernote').summernote({
            placeholder: '내용을 입력하세요',
            tabsize: 2,
            height: 300
        });
        </script>
    </div>
    <input type="submit" value="답변등록">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}
</body>
</html>

templates/pybo/question_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
</head>
<body>
{% extends 'base.html' %}
{% block content %}

<div class="container my-1 border">
  <h5 class="my-3 border-bottom pb-2">게시글쓰기</h5>

  <form method="post">
    {% csrf_token %}
      <div class="form-group">
          <input id="inputTitle" placeholder="제목을 입력하세요" name="subject" style="width:100%;"/>

          <textarea id="summernote" class="form-control" name="content">
              {{ form.content.value|default_if_none:'' }}
          </textarea>
          <script>
            $('#summernote').summernote({
              placeholder: '내용을 입력하세요',
              tabsize: 2,
              height: 300
            });
          </script>
      </div>
    <button type="submit" class="btn btn-warning">저장하기</button>
  </form>
</div>

{% endblock %}
</body>
</html>

templates/pybo/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vita Board</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}

      <div id="container-5">
        <div id="left-sidebar">

          <div id="wrapper" style="width=100%;">
              <div style="width:10%; height:80%; float:left;">
                  <div class="topbar" style="position: absolute; margin-left:50px; top:25%;">
                  <div class="left_sub_menu">
                      <div class="sub_menu">
                      <ul class="big_menu">
                          <li><button class="btn1">
                              <a class = "aa" href="{% url 'main:product' %}">상품</a>
                          </button></li>
                          <li><button class="btn1"><a class = "aa" href="{% url 'main:price' %}">가격 랭킹</a></button></li>
                          <li><button class="btn1"><a class = "aa" href="{% url 'main:contentform' %}">함유량 랭킹</a></button></li>
                          <li><button class="btn1"><a class = "aa" href="{% url 'pybo:question' %}">게시판</a></button></li>
                          <li><button class="btn1"><a class = "aa" href="{% url 'main:mypage' %}">마이 페이지</a></button></li>
                      </ul>
                      </div>
                  </div>
              </div>

              </div>

          <br>
          <br>
          <hr>
          </div>

        </div>
        <div id="center-sidebar" style="text-align:center">
            <div style="text-align:right; margin:auto;">
                <div class="col-4">
                    <div class="input-group" style="">
                        <input type="text" id="search_kw" placeholder="제목 OR 내용" class="form-control" value="{{ kw|default_if_none:''}}">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                        </div>
                    </div>
                </div>

            </div>

            <div class="container my-3">
                <table class="table">
                    <thead>
                    <tr class ="table-warning text-center">
                        <th>번호</th>
                        <th>제목</th>
                        <th>작성자</th>
                        <th>작성일시</th>
                        <th>조회수</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if question_list %}
                            {% for question in question_list %}
                                <tr class="text-center">
                                    <td>{{forloop.counter}}</td>
                                    <td>
                                        <a href="{% url 'pybo:detail' question.id %}">
                                            {{ question.subject }}
                                            {% if question.answer_set.count > 0 %}
                                                <span class="text-danger small ml-2">
                                                    {{question.answer_set.count}}
                                                </span>
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td>{{question.author.username}}</td>
                                    <td>
                                        {{question.create_date}}
                                    </td>
                                    <td>{{question.hits}}</td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="7">로그인시 이용가능합니다.</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
                <!-- 페이징처리 -->
                <ul class="pagination justify-content-center">
                    <!-- 이전페이지 -->
                    {% if question_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ question_list.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    {% for page_number in question_list.paginator.page_range %}
                    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                    {% if page_number == question_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    <!-- 다음페이지 -->
                    {% if question_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ question_list.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                  <!-- 페이징처리 끝 -->
                <a href="{% url 'pybo:question_create' %}" class ="btn btn-primary">요청 등록하기</a>
            </div>
        </div>
        <div id="right-sidebar"></div>
    </div>
    {% endblock %}
</body>
</html>