common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

#. 점은 현재의 디렉토리

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')


]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo import views
from main import views
#ex) path('main/', include('main.urls')), 메인에있는 폴더의 url을 가져오겟다

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    #path('main/', include('main.urls')),
    path('', views.main, name='main'),
    path('v1/', include('v1.urls')),
    #path('', include('main.urls')),
    path('contentform/', views.contentform, name='contentform'),
    path('price/', views.price, name='price'),
    path('pindex/', views.pindex, name='pindex'),
    #path('pybo/mypage/', views.mypage, name='mypage'),
    #path('', views.index, name='index'),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/change_password/', views.change_password, name='change_password'),
]

main/urls.py
from .views import *
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name = 'main'  #네임스페이스 추가

urlpatterns = [
    path('', views.main, name='main'),
    path('product', views.pindex, name="product"),
    path('contentform', views.contentform, name="contentform"),
    path('price', views.price, name="price"),
    #path('pindex', views.pindex, name="pindex"),
    path('mypage/', views.mypage, name='mypage'),
    path('mypage/change_password/', views.change_password, name='change_password'),
    path('product/<int:pdb_id>/', views.detail, name='pdetail'),

]

v1/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'v1'  #네임스페이스 추가

urlpatterns = [
    path('', index, name='index'),
]

templates/base.html
.{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- 반응형 적용 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- 개발자가 만든 pybo CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'style.js' %}">
         <!-- bootstrap 자바스크립트 적용 -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <script>
    $(function () {
        $(".left_sub_menu").hide();
        $(".has_sub").click(function () {
            $(".left_sub_menu").fadeToggle(300);
        });
        // 왼쪽메뉴 드롭다운
        $(".sub_menu ul.small_menu").hide();
        $(".sub_menu ul.big_menu").click(function () {
            $("ul", this).slideToggle(300);
        });
        // 외부 클릭 시 좌측 사이드 메뉴 숨기기
        $('.overlay').on('click', function () {
            $('.left_sub_menu').fadeOut();
            $('.hide_sidemenu').fadeIn();
        });
    });
</script>
    <title>base</title>
</head>


<body>
    <!-- 내비게이션바 추가-->
    <nav class="navbar navbar-expand-lg navbar-light bg-warning border-bottom">
        <a class="navbar-brand" href="{% url 'main:main' %}">
            <img src="{% static 'nanavar.png' %}." alt="image" width="170" height="35">
        </a>
        <form class="col form-inline">
            <div class="mx-auto my-auto input-group" style="width:400px;">
                <input class="form-control rounded-pill mr-sm-2" type="search" placeholder="검색어 입력" aria-label="Search">
                <button class="btn btn-outline-light my-2 my-sm-0 bg-light text-warning" type="submit">검색<i class="bi bi-search"></i></button>

            </div>

        </form>
        <!-- 토글이 버튼 햄버거모양-->
        <button class="navbar-toggle ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
        aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}}님(로그아웃)</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <!-- 기본 템플릿 안에 삽입될 내용-->
    {% block content %}
    {% endblock %}


    <hr>



    <!-- 먼저 jquery 자바스크립트 적용 -->
    <script src="{% static 'jquery-3.6.3min.js' %}"></script>


</body>
<script>

</script>
</html>

templates/form_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

</body>
</html>